services:
  app:
    container_name: gleeam-sqlite-dev
    image: gleeam-sqlite-dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
      - db-data:/data
    env_file:
      - ./env/.env.dev
    stdin_open: true
    tty: true
    command: sleep infinity
  migrator:
    container_name: gleeam-migrator-dev
    image: gleeam-migrator-dev
    build:
      context: .
      dockerfile: migration/Dockerfile
    volumes:
      - ./migration:/workspace
      - db-data:/data
    stdin_open: true
    tty: true

volumes:
  db-data:
