services:
  app:
    container_name: gleeam-sqlite-dev
    image: gleeam-sqlite-dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
      - db-data:/data
    stdin_open: true
    tty: true
    command: sleep infinity

volumes:
  db-data:
