services:
  app:
    container_name: gleeam-sqlite-prod
    image: gleeam-sqlite-prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - db-data:/data
    ports:
      - 18000:18000
    env_file:
      - ./env/.env.prod

volumes:
  db-data:
